### ISSUE TITLE
After deployment succeeded, and make the Authorization, the below error occurs

### ISSUE THREAD

**Issue by HelmyMo7amed** [PeterKlapwijk/Microsoft-Logic-Apps#3]
{
  "status": 401,
  "message": "The connection does not contain an access token. Please edit the connection and login.",
  "error": {
    "message": "The connection does not contain an access token. Please edit the connection and login."
  },
  "source": "keyvault-eus.azconn-eus-003.p.azurewebsites.net"
}

**Comment by PeterKlapwijk** [comment]
Sorry for the late response, but in which Logic App doe you see this?

Regards,

Peter

**Comment by PeterKlapwijk** [comment]
Unable to reproduce.

**Comment by PeterKlapwijk** [comment]
Unable to reproduce and no response.
