### ISSUE TITLE
Location Hard-Coded in Bicep File

### ISSUE THREAD

**Issue by tldtech** [PeterKlapwijk/Microsoft-Logic-Apps#4]
Monitor your Microsoft 365 licenses with Logic Apps -> Bicep -> MonitorLicense-connections.bicep
Line 26 has "id: '${subscription().id}/providers/Microsoft.Web/locations/westeurope/managedApis/${connections_office365_name}'"
"westeurope" is a hard-coded location and causes deployments to fail.

**Comment by PeterKlapwijk** [comment]
Thanks, @ScaryTerry177 I see I made that mistake also in other connection files. Fixed it for this one and I'm going to fix it in others.

**Comment by tldtech** [comment]
Thank you very much!
