### ISSUE TITLE
Mismatched case in Bicep folder

### ISSUE THREAD

**Issue by mjpagan** [PeterKlapwijk/Microsoft-Logic-Apps#5]
I found when running the script that it would fail with the error: An error occurred reading file. Could not find a part of the path '/home/mike/Microsoft-Logic-Apps/Monitor your Microsoft 365 licenses with Logic Apps/bicep/MonitorLicense-root.bicep'.

Looking at the folder in the repository, it is Bicep not bicep. After making a copy of the deploy script and modifying the script to match the case of the folder it ran successfully.

**Comment by PeterKlapwijk** [comment]
Sorry for my late response.
Thanks for noticing this, it is fixed.
